#!/bin/bash
# script to restore the dots and pkgs i use.
# based on hexdsl's hextool script https://git.hexdsl.co.uk/hexdsl/dots/src/master/hextool
pwdCache=$(pwd)
me="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
u="$USER"

menu(){
	echo "usage:    dotgett [OPTION]"
	echo " "
	echo "init:     Install the basics (git,ssh,wget,curl,build-essentail)"
	echo "dots:     Get dots files from codeberg and place into ~/git/"
	echo "suckmore: download builds of suckless software and place in ~/Git"
	echo "gitgett:  Get git repos from codeberg and place into ~/git/"
	echo "stow:     Restore Stow form dots"
	echo "apts:     Use 'apt' to setup reposs"
	echo "hug:      We all need one sometimes"
	echo "syms:     symlink files and folders to the corret places"
	echo "all:      All of above"
	echo " "
	echo " "
	echo "INFORMATION! - options are shown in 'best' order for new install."
	}

init(){
	sudo apt install git ssh wget curl build-essential
	mkdir ~/Git/sealeaf
	mkdir ~/Git/3rdparty
	mkdir -p ~/.config/mpv/watch_later
	}

suckmore(){
	git clone https://codeberg.org/sealeaf/st.git ~/Git/sealeaf/st
	git clone https://codeberg.org/sealeaf/suckmore.git ~/Git/sealeaf/suckmore
	}

hug(){
	    clear
	    echo " "
	    title="((((((((( hug )))))))))"
	    printf "%*s\n" $(((${#title}+$COLUMNS)/2)) "$title"
	    echo " "
	    echo "everything is going to be okay buddy!"
	    echo " "
	}

dots(){
		cd ~
		git clone --remote-submodules --recurse-submodules https://codeberg.org/sealeaf/dots.git ~/Git/sealeaf/dots
	}

stow(){
	echo "Clearing out mimeapps"
	mv -v ~/.config/mimeapps.list ~/.config/mimeapps.list.backup
	cat /dev/null | tee ~/.config/mimeapps.list

	# $HOME
	echo "Stowing dots to $HOME"
	cd ~/Git/bigowo/dots/stow_home/
	stow --restow -vt ~ *
	cd ~/Git/bigowo/dots

     # $ROOT
	echo "Setting up $ROOT files."
	sudo cp -v stow_root/bash/root/.bashrc /root/.bashrc
	}

apt(){
	echo "Downloading Sources.list and Sources.list.d/*.list"
	curl https://codeberg.org/sealeaf/dots/raw/branch/main/pkgs/sources.list | sudo tee /etc/apt/sources.list
	curl https://codeberg.org/sealeaf/dots/raw/branch/main/pkgs/sources.list.d/adoptopenjdk.list | sudo tee /etc/apt/sources.list.d/adoptopenjdk.list
	curl https://codeberg.org/sealeaf/dots/raw/branch/main/pkgs/sources.list.d/lutris.list | sudo tee /etc/apt/sources.list.d/lutris.list
	curl https://codeberg.org/sealeaf/dots/raw/branch/main/pkgs/sources.list.d/riot-im.list | sudo tee /etc/apt/sources.list.d/riot-im.list
	curl https://codeberg.org/sealeaf/dots/raw/branch/main/pkgs/sources.list.d/vscodium.list | sudo tee /etc/apt/sources.list.d/vscodium.list
	curl https://codeberg.org/sealeaf/dots/raw/branch/main/pkgs/sources.list.d/winehq.list | sudo tee /etc/apt/sources.list.d/winehq.list
	sudo apt update
	sudo apt upgrade --fix-broken
	}

syms(){
	read -p "Are you sure? THIS WILL DELETE MANY THINGS and symlink them to nextcloud folders [y/N]" -n 1 -r
	echo
	if [[ ! $REPLY =~ ^[Yy]$ ]]
	then
	    exit 1
	fi
	# The "rm"ing
	rm -rf ~/{Pictures,Documents,Desktop,Music,Notes,.ssh,Videos,Applications}
	mkdir /mnt/{Games,Data,USB,remote}
	ln -sf /mnt/Data/Nextcloud ~/Nextcloud
	ln -sf /mnt/Games/ ~/Games
	ln -sf /mnt/Games/steam ~/.steam
    ln -sf /mnt/Data/Nextcloud/Applications ~/Applications
	ln -sf /mnt/Data/Nextcloud/Pictures/ ~/Pictures
	ln -sf /mnt/Data/Nextcloud/Documents ~/Documents
	ln -sf /mnt/Data/Nextcloud/Desktop ~/Desktop
	ln -sf /mnt/Data/Nextcloud/Downloads ~/Downloads
	ln -sf /mnt/Data/Nextcloud/Music ~/Music
    ln -sf /mnt/Data/Nextcloud/Notes ~/Notes
	# ssh
	ln -s ~/Nextcloud/.ssh/ ~/.ssh
	chmod 600 ~/.ssh/id_rsa

	echo "--------------------------------------"
	echo "You may want to run 'pass init $u' now"
    }

all(){
	hug
	init
	suckmore
	dots
	stow
	apt
	sym
	hug
}

if [ -n "$1" ]; then
  $1
else
  menu
fi

